// .claude/skills/macroglobal-design/components/nav/PageHeader.jsx
import React from 'react';

/**
 * MACRO Global CRM — PageHeader
 * Standard module header: icon plaque + title (+ optional subtitle) on the start,
 * actions on the end. Used at the top of every work surface (Deals, Contacts,
 * Tasks, Settings…). Sits on a card surface, separated by a bottom border.
 */
export function PageHeader({ icon, title, subtitle, actions, style }) {
  return (
    <header style={{
      display: 'flex', alignItems: 'center', gap: '14px', padding: '14px 22px',
      borderBottom: '1px solid var(--mg-border-default)', background: 'var(--mg-surface-card)',
      flexShrink: 0, flexWrap: 'wrap', fontFamily: 'var(--mg-font-sans)', ...style,
    }}>
      {icon && (
        <span style={{
          width: 38, height: 38, borderRadius: 'var(--mg-radius-md)', background: 'var(--mg-primary-100)',
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
        }}>
          <i className={'pi ' + icon} style={{ fontSize: '17px', color: 'var(--mg-primary-900)' }} />
        </span>
      )}
      <div style={{ minWidth: 0 }}>
        <h1 style={{ fontSize: '19px', fontWeight: 600, color: 'var(--mg-text-primary)', margin: 0, lineHeight: 1.1 }}>{title}</h1>
        {subtitle && <div style={{ fontSize: '12px', color: 'var(--mg-text-muted)', marginTop: '2px' }}>{subtitle}</div>}
      </div>
      <span style={{ flex: 1, minWidth: 12 }} />
      {actions}
    </header>
  );
}

// front/src/components/AppShell/PageHeader.vue
<template>
  <header class="page-header">
    <div class="page-header__left">
      <i v-if="icon" :class="['page-header__icon', icon]" />
      <div class="page-header__titles">
        <h1 class="page-header__title">{{ title }}</h1>
        <slot name="subtitle"><p v-if="subtitle" class="page-header__subtitle">{{ subtitle }}</p></slot>
      </div>
    </div>
    <div v-if="$slots.actions" class="page-header__actions">
      <slot name="actions" />
    </div>
  </header>
</template>

<script setup lang="ts">
defineProps<{
  title: string
  subtitle?: string
  icon?: string
}>()
</script>

<style lang="scss" scoped>
.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: $space-4;
  padding: $space-4 $space-6;
  background-color: $surface-card;
  border-bottom: 1px solid $surface-200;
  min-height: 56px;
  flex-shrink: 0;
}

.page-header__left {
  display: flex;
  align-items: center;
  gap: $space-3;
  min-width: 0;
}

.page-header__icon {
  font-size: $font-size-xl;
  color: $primary-900;
  flex-shrink: 0;
}

.page-header__titles {
  min-width: 0;
}

.page-header__title {
  font-size: $font-size-xl;
  font-weight: $font-weight-semibold;
  color: $surface-900;
  margin: 0;
  line-height: $line-height-tight;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.page-header__subtitle {
  font-size: $font-size-sm;
  color: $surface-600;
  margin: 2px 0 0;
  line-height: $line-height-normal;
}

.page-header__actions {
  display: flex;
  align-items: center;
  gap: $space-2;
  flex-shrink: 0;
}
</style>
